#!/usr/bin/env bash
# generate_public_docs.sh — generate public-safe capability status doc from private rich docs
# Reads private docs/SDK_DA_COMPLETION_PLAN.md and emits a stripped docs/CAPABILITY_STATUS.md
# suitable for the public mirror.
# Run from repo root: bash scripts/generate_public_docs.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

SRC="docs/SDK_DA_COMPLETION_PLAN.md"
OUT="docs/CAPABILITY_STATUS.md"

if [[ ! -f "$SRC" ]]; then
  echo "SKIP: $SRC not found (already stripped for public?) — no-op" >&2
  exit 0
fi

echo "==> generate_public_docs: building $OUT from $SRC"

# Extract the three canonical sections from SDK_DA_COMPLETION_PLAN.md.
# Rule: strip operator-private language; keep "Supported / Preview-Gated / Upstream-Gap"
# but rename to public-safe headings.

python3 - "$SRC" "$OUT" << 'PYEOF'
import sys, re, pathlib

src_path = pathlib.Path(sys.argv[1])
out_path = pathlib.Path(sys.argv[2])

text = src_path.read_text()

# Map private section headers → public headers
section_map = {
    r"^##\s+Supported( Today)?": "## Supported",
    r"^##\s+Preview.Gated": "## Not Yet Supported (Preview)",
    r"^##\s+Upstream.Gap": "## Not Planned (Upstream Gap)",
}

lines = text.splitlines()
output = [
    "# DSK Capability Status",
    "",
    "Capabilities listed here are those wired in the declarative-sdk-for-k and",
    "verified against Keeper Commander 17.2.16. Features in lower sections are",
    "not supported in the current release.",
    "",
    "<!-- Auto-generated by scripts/generate_public_docs.sh. Do not edit directly. -->",
    "",
]

current_section = None
for line in lines:
    # Skip title — we wrote our own
    if re.match(r"^#\s+DSK", line):
        continue
    # Skip private metadata lines
    if re.match(r"^Status date:", line):
        continue
    # Remap section headers
    matched = False
    for pattern, replacement in section_map.items():
        if re.match(pattern, line, re.IGNORECASE):
            output.append(replacement)
            current_section = replacement
            matched = True
            break
    if matched:
        continue
    # Strip operator-private language in content lines
    # Replace "upstream-gap" / "preview-gated" with public-safe text
    line = re.sub(r"\bupstream.gap\b", "not planned (upstream gap)", line, flags=re.IGNORECASE)
    line = re.sub(r"\bpreview.gated\b", "not yet supported", line, flags=re.IGNORECASE)
    output.append(line)

out_path.write_text("\n".join(output) + "\n")
print(f"Written {out_path} ({len(output)} lines)")
PYEOF

echo "==> generate_public_docs: done → $OUT"
